export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gray-900">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-white mb-4">About Codebreaker Quest</h1>
          <p className="text-xl text-gray-400">
            A fair and transparent puzzle-solving experience
          </p>
        </div>

        <div className="space-y-8">
          {/* Fairness Section */}
          <div className="card p-8">
            <h2 className="text-2xl font-semibold text-white mb-4">Fairness & Transparency</h2>
            <div className="prose prose-invert max-w-none">
              <p className="text-gray-300 mb-4">
                Codebreaker Quest is designed to be completely fair and transparent. Here&apos;s how we ensure 
                a level playing field for all participants:
              </p>
              
              <ul className="space-y-3 text-gray-300">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>No Hidden Information:</strong> All puzzle clues and hints are visible to everyone. No external resources or special knowledge is required.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>Deterministic Validation:</strong> Answers are validated using cryptographic hashing, ensuring consistent and fair evaluation.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>Client-Side Only:</strong> Everything runs in your browser. No server-side validation or hidden logic.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>Progress Persistence:</strong> Your progress is saved locally and can be resumed at any time.</span>
                </li>
              </ul>
            </div>
          </div>

          {/* Safety Section */}
          <div className="card p-8">
            <h2 className="text-2xl font-semibold text-white mb-4">Safety & Security Notes</h2>
            <div className="prose prose-invert max-w-none">
              <div className="bg-yellow-900/20 border border-yellow-700 rounded-lg p-4 mb-6">
                <div className="flex items-start">
                  <svg className="w-5 h-5 text-yellow-400 mr-3 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
                  </svg>
                  <div>
                    <h3 className="text-yellow-400 font-semibold mb-2">Important Security Warning</h3>
                    <p className="text-yellow-100 text-sm">
                      The final key generated by this puzzle is for educational purposes only. 
                      <strong> Never use it for any real cryptocurrency transactions or store valuable assets.</strong>
                    </p>
                  </div>
                </div>
              </div>

              <p className="text-gray-300 mb-4">
                This website is designed as an educational puzzle experience. Here are important security considerations:
              </p>
              
              <ul className="space-y-3 text-gray-300">
                <li className="flex items-start">
                  <span className="text-red-400 mr-3 mt-1">•</span>
                  <span><strong>Educational Purpose Only:</strong> This is a demonstration of cryptographic concepts, not a real wallet generator.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-400 mr-3 mt-1">•</span>
                  <span><strong>No Real Value:</strong> The generated key should never be used for actual cryptocurrency transactions.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-400 mr-3 mt-1">•</span>
                  <span><strong>Client-Side Generation:</strong> All puzzle logic runs in your browser, making it transparent but not secure for real use.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-400 mr-3 mt-1">•</span>
                  <span><strong>No Backend Storage:</strong> We don&apos;t store any of your answers or progress on our servers.</span>
                </li>
              </ul>
            </div>
          </div>

          {/* Technical Details */}
          <div className="card p-8">
            <h2 className="text-2xl font-semibold text-white mb-4">Technical Implementation</h2>
            <div className="prose prose-invert max-w-none">
              <p className="text-gray-300 mb-4">
                For those interested in the technical details of how this puzzle system works:
              </p>
              
              <ul className="space-y-3 text-gray-300">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>Answer Validation:</strong> Uses SHA-256 hashing to validate answers without storing plaintext.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>Progress Storage:</strong> Uses localStorage to persist completed puzzles locally.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>Fragment Assembly:</strong> Final key is built by concatenating unlocked fragments in order.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-3 mt-1">•</span>
                  <span><strong>No External Dependencies:</strong> Runs entirely client-side with standard web APIs.</span>
                </li>
              </ul>
            </div>
          </div>

          {/* Contact/Support */}
          <div className="card p-8">
            <h2 className="text-2xl font-semibold text-white mb-4">Questions or Issues?</h2>
            <div className="prose prose-invert max-w-none">
              <p className="text-gray-300 mb-4">
                If you encounter any issues or have questions about the puzzles:
              </p>
              
              <ul className="space-y-2 text-gray-300">
                <li>• All puzzles are designed to be solvable with the information provided</li>
                <li>• Answers are case-insensitive and whitespace is automatically trimmed</li>
                <li>• Progress is saved automatically in your browser&apos;s localStorage</li>
                <li>• You can clear your progress by clearing your browser&apos;s local storage</li>
              </ul>
              
              <p className="text-gray-400 text-sm mt-6">
                Remember: This is an educational experience. Take your time, think creatively, 
                and enjoy the challenge!
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
